# ====================================================
# ChatGe3ks Configuration
# ====================================================

# ---------------
# General Settings
# ---------------

# Enable debug logging (more verbose output)
debug: false

# Duration (in seconds) for which a new player's welcome window remains active.
# Min: 5, Max: 3600 (1 hour)
welcome-window: 60

# ---------------------
# Redis Configuration
# ---------------------
# Used for cross-server communication and first-join detection
redis:
  # Redis server address
  host: "redis-12757.c44.us-east-1-2.ec2.redns.redis-cloud.com"

  # Redis server port
  port: 12757

  # Redis password
  password: "2hBxjuHQtVo1cGhJ5vLUd9giBiLMV7Un"

  # Connection timeout in milliseconds
  timeout: 2000

# -------------------------
# Message Format Settings
# -------------------------
# You can use color codes with & symbol
messages:
  prefix: "&8[&6ChatGe3ks&8] &r"
  reward: "${prefix}&aYou received a reward for welcoming a new player!"