# ChatGe3ks default configuration

redis:
  host: "redis-12757.c44.us-east-1-2.ec2.redns.redis-cloud.com"
  port: 12757
  user: "default"
  password: "2hBxjuHQtVo1cGhJ5vLUd9giBiLMV7Un"

# Duration (in seconds) for which a new player's welcome window remains active.
welcome-window: 60
